# Generated by Django 4.2.4 on 2023-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_federal', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Федеральные округа',
                'verbose_name_plural': 'Федеральные округа',
            },
        ),
        migrations.CreateModel(
            name='ForestCareActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_activities', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Мероприятия по уходу за лесами',
                'verbose_name_plural': 'Мероприятия по уходу за лесами',
            },
        ),
        migrations.CreateModel(
            name='MethodForestRestoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_method', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Метод лесовосстановления',
                'verbose_name_plural': 'Метод лесовосстановления',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recommendation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Рекомендации по результатам натурных обследований',
                'verbose_name_plural': 'Рекомендации по результатам натурных обследований',
            },
        ),
    ]
