# Generated by Django 4.1.2 on 2022-11-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0002_districtforestly_id_forestly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='id_subject_RF',
        ),
        migrations.AlterField(
            model_name='listregion',
            name='soil_lot',
            field=models.CharField(max_length=300, verbose_name='Выдел'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
