# Generated by Django 4.1 on 2023-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0003_accordancemolodkrandtppl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodforestrestoration',
            name='name_method',
            field=models.CharField(max_length=600),
        ),
    ]
