# Generated by Django 4.1.3 on 2022-11-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0003_remove_branches_id_subject_rf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarter',
            options={'verbose_name': 'Квартал', 'verbose_name_plural': 'Квартал'},
        ),
        migrations.AlterField(
            model_name='sample',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата пробы'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.profile', verbose_name='Сотрудник '),
        ),
        migrations.AlterField(
            model_name='subjectrf',
            name='name_subject_RF',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименования субъекта РФ'),
        ),
    ]
