# Generated by Django 4.1.3 on 2022-11-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0004_alter_quarter_options_alter_sample_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrf',
            name='name_subject_RF',
            field=models.CharField(max_length=255, verbose_name='Наименования субъекта РФ'),
        ),
    ]
