# Generated by Django 4.1 on 2023-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0004_alter_methodforestrestoration_name_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_forest_district', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Лесные районы РФ',
                'verbose_name_plural': 'Лесные районы РФ',
            },
        ),
    ]
