# Generated by Django 4.1.3 on 2023-09-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0005_forestdistricts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcard',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер приказа'),
            preserve_default=False,
        ),
    ]
