# Generated by Django 4.1.3 on 2022-11-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0005_alter_subjectrf_name_subject_rf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarter',
            name='id_forestly',
        ),
        migrations.AddField(
            model_name='quarter',
            name='id_district_forestly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.districtforestly', verbose_name='Лесничество'),
        ),
    ]
