# Generated by Django 4.1 on 2023-09-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0006_fieldcard_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldcard',
            old_name='number',
            new_name='number_order',
        ),
    ]
