# Generated by Django 4.1.3 on 2022-12-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0007_accordancemolodkrandtppl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='id_forestly',
        ),
    ]
