# Generated by Django 4.2.5 on 2023-10-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0007_rename_number_fieldcard_number_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericNameBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_generic', models.CharField(max_length=150, verbose_name='Родовое название породы')),
            ],
            options={
                'verbose_name': 'Родовое название породы',
                'verbose_name_plural': 'Родовые названия пород',
            },
        ),
        migrations.CreateModel(
            name='LifeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_life', models.CharField(max_length=100, verbose_name='Наименование жизненной формы')),
            ],
            options={
                'verbose_name': 'Жизненная форма',
                'verbose_name_plural': 'Жизненные формы',
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='latin_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Латинское наименование'),
        ),
        migrations.AddField(
            model_name='breed',
            name='life_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.lifeform', verbose_name='Жизненна форма'),
        ),
    ]
