# Generated by Django 4.1.3 on 2022-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0008_checktrigger_remove_breed_id_forestly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=False)),
            ],
        ),
    ]
