# Generated by Django 4.2.5 on 2023-10-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0008_genericnamebreed_lifeform_breed_latin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='generic_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.genericnamebreed', verbose_name='Родовое название породы'),
        ),
    ]
