# Generated by Django 4.1 on 2023-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0009_breed_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcard',
            name='lands_other',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
