# Generated by Django 4.1.3 on 2022-12-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0010_checkaltertables_delete_checktrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='CheckAlterTables',
        ),
        migrations.AlterField(
            model_name='quarter',
            name='id_district_forestly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.districtforestly', verbose_name='Участковое лесничество'),
        ),
    ]
