# Generated by Django 4.1 on 2023-10-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0010_fieldcard_lands_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='ShortName',
            field=models.CharField(max_length=50, null=True, verbose_name='Сокр.'),
        ),
    ]
