# Generated by Django 4.1.3 on 2023-01-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0011_checktrigger_photopoint_delete_checkaltertables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('token', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photopoint',
            options={'verbose_name': 'Фото точка', 'verbose_name_plural': 'Фото точка'},
        ),
        migrations.AddField(
            model_name='breed',
            name='is_foliar',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='is_pine',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('map', models.CharField(max_length=1)),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.profile', verbose_name='Профиль')),
            ],
        ),
    ]
