# Generated by Django 4.1 on 2023-10-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0011_alter_breed_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='economy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.economy', verbose_name='Хозяйство'),
        ),
    ]
