# Generated by Django 4.1 on 2023-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0012_breed_economy'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='evergreen',
            field=models.IntegerField(null=True, verbose_name='Вечнозеленость'),
        ),
    ]
