# Generated by Django 4.1.3 on 2023-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0012_users_alter_photopoint_options_breed_is_foliar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трекинг', 'verbose_name_plural': 'Трекинг'},
        ),
        migrations.AlterField(
            model_name='breed',
            name='is_foliar',
            field=models.BooleanField(default=0, null=True, verbose_name='Лиственное'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='is_pine',
            field=models.BooleanField(default=0, null=True, verbose_name='Хвойное'),
        ),
    ]
