# Generated by Django 4.1.3 on 2023-01-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0013_alter_track_options_alter_breed_is_foliar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='token',
        ),
        migrations.AddField(
            model_name='breed',
            name='ShortName',
            field=models.CharField(max_length=10, null=True, verbose_name='Сокр.'),
        ),
        migrations.AddField(
            model_name='breed',
            name='main',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.users', verbose_name='Пользователь'),
        ),
    ]
