# Generated by Django 4.1 on 2023-10-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0013_breed_evergreen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='ShortName',
            new_name='short_name',
        ),
    ]
