# Generated by Django 4.1 on 2023-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0014_rename_shortname_breed_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='latin_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Латинское наименование'),
        ),
    ]
