# Generated by Django 4.1.3 on 2023-01-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0014_remove_users_token_breed_shortname_breed_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undergrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименовапние')),
            ],
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Лесообразующие породы', 'verbose_name_plural': 'Лесообразующие породы'},
        ),
        migrations.AddField(
            model_name='list',
            name='avg_diameter',
            field=models.FloatField(null=True, verbose_name='Средний диаметр'),
        ),
        migrations.AddField(
            model_name='list',
            name='avg_height',
            field=models.FloatField(null=True, verbose_name='Средняя высота'),
        ),
        migrations.AddField(
            model_name='list',
            name='count_of_plants',
            field=models.IntegerField(null=True, verbose_name='Количество растений для подлеска'),
        ),
        migrations.AlterField(
            model_name='list',
            name='max_height',
            field=models.FloatField(null=True, verbose_name='Максимальная высота'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name='UndergrowthByDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.profile', verbose_name='Профиль')),
                ('id_undergrowth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.undergrowth', verbose_name='Подлесок')),
            ],
            options={
                'verbose_name': 'Подлесок по умолчанию',
                'verbose_name_plural': 'Подлесок по умолчанию',
            },
        ),
        migrations.CreateModel(
            name='ForestFormingByDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.breed', verbose_name='Порода')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='id_undergrowth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.undergrowth', verbose_name='Подлесок'),
        ),
    ]
