# Generated by Django 4.1.3 on 2023-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0015_undergrowth_alter_breed_options_list_avg_diameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forestformingbydefault',
            options={'verbose_name': 'Лесообразующие породы по умолчанию'},
        ),
        migrations.AlterModelOptions(
            name='undergrowth',
            options={'verbose_name': 'Подлесок'},
        ),
        migrations.RemoveField(
            model_name='breed',
            name='main',
        ),
        migrations.AddField(
            model_name='list',
            name='main',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='listregion',
            name='mark_del',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='lenght',
            field=models.FloatField(null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='sample',
            name='square',
            field=models.FloatField(null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='sample',
            name='width',
            field=models.FloatField(null=True, verbose_name='Ширина'),
        ),
    ]
