# Generated by Django 4.1 on 2023-11-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0016_users_groups_users_is_active_users_subject_rf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subject_rf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.subjectrf'),
        ),
    ]
