# Generated by Django 4.1.3 on 2023-02-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0016_alter_forestformingbydefault_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_working_breeds',
        ),
    ]
