# Generated by Django 4.1.3 on 2023-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0018_photopoint_id_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listregion',
            name='mark_del',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
