# Generated by Django 4.1 on 2023-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0019_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcard',
            name='number_order',
            field=models.IntegerField(null=True, verbose_name='Номер приказа'),
        ),
    ]
