# Generated by Django 4.1.3 on 2023-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0020_alter_listregion_mark_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listregion',
            name='sample_region',
            field=models.FloatField(max_length=300, verbose_name='Плошадь участка, га'),
        ),
    ]
