# Generated by Django 4.1 on 2023-11-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0020_alter_fieldcard_number_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcard',
            name='lands_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcard',
            name='plot_farm_referring_land',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Участок хозяйству при отнесении к землям'),
        ),
    ]
