# Generated by Django 4.1.3 on 2023-03-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0021_alter_listregion_sample_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='avg_height_undergrowth',
            field=models.FloatField(null=True, verbose_name='Средняя высота подлеска'),
        ),
    ]
