# Generated by Django 4.1 on 2023-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0022_alter_users_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionregion',
            name='economy_act_land',
            field=models.CharField(max_length=500, null=True, verbose_name='Хозяйство по Акту отнесения земель'),
        ),
    ]
