# Generated by Django 4.1.3 on 2023-04-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0023_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='point7Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_composition', models.IntegerField()),
                ('breed', models.IntegerField()),
                ('age', models.IntegerField()),
                ('avg_height', models.IntegerField()),
                ('avg_diameter', models.IntegerField()),
                ('count_register_wood_plants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='point7Table2Sapling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_composition', models.IntegerField()),
                ('breed', models.IntegerField()),
                ('age', models.IntegerField()),
                ('avg_height', models.IntegerField()),
                ('avg_diameter', models.IntegerField()),
                ('count_register_wood_plants', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='listregion',
            name='mark_update',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='DescriptionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_assignment_land', models.DateField(verbose_name='Год отнесения к землям')),
                ('year_format_fond_trees', models.DateField(verbose_name='Год образования категории фонда лесовосстановления')),
                ('inf_restore_forest', models.CharField(max_length=500)),
                ('breed_structure_sapling_act_land', models.CharField(max_length=300)),
                ('economy_act_land', models.CharField(max_length=300)),
                ('id_list_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.listregion', verbose_name='Перечетная ведомость участка')),
                ('id_method_of_reforestation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.methodofreforestation', verbose_name='Способ лесовосстановления')),
            ],
        ),
    ]
