# Generated by Django 4.1 on 2023-12-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0023_alter_descriptionregion_economy_act_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_side', models.CharField(max_length=300)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.quarter')),
            ],
            options={
                'verbose_name': 'Дача/Урочище',
                'verbose_name_plural': 'Дача/Урочище',
            },
        ),
    ]
