# Generated by Django 4.1.3 on 2023-04-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0024_point7table_point7table2sapling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionregion',
            name='change_breed_and_structure_sapling',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='descriptionregion',
            name='recommendation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='descriptionregion',
            name='results_surtvey',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='breed_structure_sapling_act_land',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='economy_act_land',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='listregion',
            name='mark_update',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
