# Generated by Django 4.1.3 on 2023-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0025_descriptionregion_change_breed_and_structure_sapling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='is_foliar',
            field=models.IntegerField(default=0, null=True, verbose_name='Лиственное'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='is_pine',
            field=models.IntegerField(default=0, null=True, verbose_name='Хвойное'),
        ),
        migrations.AlterField(
            model_name='checktrigger',
            name='bool',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='avg_diameter',
            field=models.FloatField(default=0, null=True, verbose_name='Средний диаметр'),
        ),
        migrations.AlterField(
            model_name='list',
            name='avg_height',
            field=models.FloatField(default=0, null=True, verbose_name='Средняя высота'),
        ),
        migrations.AlterField(
            model_name='list',
            name='main',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='max_height',
            field=models.FloatField(default=0, null=True, verbose_name='Максимальная высота'),
        ),
        migrations.AlterField(
            model_name='listregion',
            name='mark_del',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listregion',
            name='mark_update',
            field=models.IntegerField(null=True),
        ),
    ]
