# Generated by Django 4.1.3 on 2023-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0026_alter_breed_is_foliar_alter_breed_is_pine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='is_foliar',
            field=models.BooleanField(default=0, null=True, verbose_name='Лиственное'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='is_pine',
            field=models.BooleanField(default=0, null=True, verbose_name='Хвойное'),
        ),
    ]
