# Generated by Django 4.1 on 2024-02-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0026_remove_listregion_id_district_forestly'),
    ]

    operations = [
        migrations.AddField(
            model_name='listregion',
            name='id_district_forestly',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.districtforestly', verbose_name='Квартал'),
        ),
    ]
