# Generated by Django 4.1 on 2024-02-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0027_listregion_id_district_forestly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='id_quarter',
        ),
        migrations.AddField(
            model_name='sample',
            name='dacha',
            field=models.CharField(max_length=300, null=True, verbose_name='Урочище'),
        ),
        migrations.AddField(
            model_name='sample',
            name='id_district_forestly',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.districtforestly', verbose_name='Участковое лесничество'),
        ),
        migrations.AddField(
            model_name='sample',
            name='name_quarter',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование квартала'),
        ),
        migrations.AlterField(
            model_name='listregion',
            name='id_district_forestly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.districtforestly', verbose_name='Квартал'),
        ),
    ]
