# Generated by Django 4.1.3 on 2023-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0027_alter_breed_is_foliar_alter_breed_is_pine'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='mark_update',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='mark_update',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
