# Generated by Django 4.1.3 on 2023-04-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0028_list_mark_update_sample_mark_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listregion',
            name='soil_lot',
            field=models.CharField(default=0, max_length=300, null=True, verbose_name='Выдел'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='soil_lot',
            field=models.CharField(default=0, max_length=300, null=True, verbose_name='Выдел'),
        ),
    ]
