# Generated by Django 4.1 on 2024-02-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0028_remove_sample_id_quarter_sample_dacha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='dacha',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='id_district_forestly',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='name_quarter',
        ),
    ]
