# Generated by Django 4.1 on 2024-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0029_remove_sample_dacha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcard',
            name='respond_farm',
            field=models.BooleanField(default=False, verbose_name='Соответствует хозяйству.'),
        ),
    ]
