# Generated by Django 4.1.3 on 2023-04-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0029_alter_listregion_soil_lot_alter_sample_soil_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopoint',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='photopoint',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='photopoint',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lenght',
            field=models.FloatField(default=0, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='square',
            field=models.FloatField(default=0, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='width',
            field=models.FloatField(default=0, null=True, verbose_name='Ширина'),
        ),
    ]
