# Generated by Django 4.1.3 on 2023-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0030_photopoint_date_photopoint_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopoint',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='photopoint',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
