# Generated by Django 4.1.3 on 2024-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0031_czl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_area',
            field=models.FloatField(null=True, verbose_name='Площадь пробы, га'),
        ),
    ]
