# Generated by Django 4.1.3 on 2023-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0031_alter_photopoint_latitude_alter_photopoint_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopoint',
            name='latitude',
            field=models.FloatField(blank=True, verbose_name='Широта'),
        ),
    ]
