# Generated by Django 4.1 on 2024-03-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0031_czl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czl',
            name='id_main_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_subject', to='djangoForest.subjectrf', verbose_name='Главный субъект'),
        ),
        migrations.RemoveField(
            model_name='czl',
            name='id_subject',
        ),
        migrations.AddField(
            model_name='czl',
            name='id_subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slave_subject', to='djangoForest.subjectrf', verbose_name='Подчиненный субъект'),
            preserve_default=False,
        ),
    ]
