# Generated by Django 4.1.3 on 2024-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0032_alter_sample_sample_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestprotectioncategory',
            name='name_forest_protection_category',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
    ]
