# Generated by Django 4.1 on 2024-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0033_alter_czl_id_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_area',
            field=models.FloatField(null=True, verbose_name='Площадь пробы, га'),
        ),
    ]
