# Generated by Django 4.1.3 on 2024-03-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0033_alter_forestprotectioncategory_name_forest_protection_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listregion',
            name='id_district_forestly',
            field=models.ForeignKey(default=2153, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.districtforestly', verbose_name='Квартал'),
        ),
    ]
