# Generated by Django 4.1.3 on 2023-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0033_alter_photopoint_latitude_alter_photopoint_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopoint',
            name='latitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='photopoint',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота'),
        ),
    ]
