# Generated by Django 4.1.3 on 2024-05-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0034_alter_listregion_id_district_forestly'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcard',
            name='end_at',
            field=models.CharField(default=0, max_length=200, verbose_name='заканчивая до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldcard',
            name='start_at',
            field=models.CharField(default=0, max_length=200, verbose_name='начиная с'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldcard',
            name='point7_stock',
            field=models.FloatField(null=True, verbose_name='Запас'),
        ),
        migrations.AlterField(
            model_name='fieldcard',
            name='stock',
            field=models.FloatField(null=True, verbose_name='Запас'),
        ),
    ]
