# Generated by Django 4.1.3 on 2023-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0034_alter_photopoint_latitude_alter_photopoint_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopoint',
            name='date',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата'),
        ),
    ]
