# Generated by Django 4.1.3 on 2024-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0035_fieldcard_end_at_fieldcard_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcard',
            name='end_at',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='заканчивая до'),
        ),
        migrations.AlterField(
            model_name='fieldcard',
            name='start_at',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='начиная с'),
        ),
    ]
