# Generated by Django 4.1.3 on 2023-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0035_alter_photopoint_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='descriptionregion',
            name='count_plants',
            field=models.FloatField(null=True, verbose_name='Количество высаженных растений на 1 га'),
        ),
        migrations.AddField(
            model_name='descriptionregion',
            name='preservation_breed',
            field=models.CharField(max_length=300, null=True, verbose_name='сохранность культивируемой породы на момент обследования'),
        ),
        migrations.AddField(
            model_name='descriptionregion',
            name='schema_mixing_breeds',
            field=models.CharField(max_length=300, null=True, verbose_name='Схема смешения пород'),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='breed_structure_sapling_act_land',
            field=models.CharField(max_length=500, verbose_name='Породный состав молодняка по Акту отнесения земель'),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='change_breed_and_structure_sapling',
            field=models.CharField(max_length=500, null=True, verbose_name='Изменение породного и качественного состава молодняка'),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='economy_act_land',
            field=models.CharField(max_length=500, verbose_name='Хозяйство по Акту отнесения земель'),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='inf_restore_forest',
            field=models.CharField(max_length=500, verbose_name='Данные о проведенных мероприятиях по уходу за лесами'),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='recommendation',
            field=models.CharField(max_length=300, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='descriptionregion',
            name='results_surtvey',
            field=models.CharField(max_length=600, null=True, verbose_name='Вывод по результатам обследования'),
        ),
    ]
