# Generated by Django 4.1.3 on 2023-04-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0036_alter_users_options_descriptionregion_count_plants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_areas_of_forests', models.CharField(max_length=300)),
                ('rent_area', models.BooleanField(default=0)),
                ('time_of_reforestation', models.CharField(max_length=300, verbose_name='Срок проведения лесовосстановления')),
                ('point7year', models.DateField(verbose_name="['%Y']")),
                ('point7date', models.DateField()),
                ('point7number', models.IntegerField()),
                ('point7agreed', models.CharField(max_length=300)),
                ('point7_natural_composition', models.CharField(max_length=300)),
                ('point7_natural_composition2', models.CharField(max_length=300)),
                ('square_one_sample_area', models.FloatField(verbose_name='Площадь 1 пробной площади')),
                ('count_sample_area', models.IntegerField(verbose_name='Количество пробных площадей')),
                ('breed_composition', models.CharField(max_length=500, verbose_name='Породный состав')),
                ('completeness', models.CharField(max_length=300, verbose_name='Полнота')),
                ('stock', models.IntegerField(verbose_name='Запас')),
                ('conclusion', models.CharField(max_length=500, verbose_name='Заключение')),
                ('plot_farm_referring_land', models.CharField(max_length=500, verbose_name='Участок хозяйству при отнесении к землям')),
                ('recomendation', models.CharField(max_length=300, verbose_name='Рекомендации')),
                ('plot_features', models.CharField(max_length=500, verbose_name='Особенности участка')),
                ('site_survey', models.CharField(max_length=300, verbose_name='Обследование провел')),
                ('in_front', models.CharField(max_length=300, verbose_name='В присуствии')),
                ('date_and_time', models.DateTimeField(verbose_name='Дата и время обследования')),
                ('id_category_of_forest_fund_lands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.categoryofforestfundlands', verbose_name='Категория земель лесного фонда')),
                ('id_economy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.economy', verbose_name='Хозяйство')),
                ('id_forest_protection_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.forestprotectioncategory', verbose_name='Категория защитных лесов')),
                ('id_list_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.listregion', verbose_name='Перечетная ведомость участка')),
                ('id_method_of_reforestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.methodofreforestation', verbose_name='Способ лесовосстановления')),
                ('id_point7_table2_sapling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.point7table2sapling', verbose_name='Таблица 2 молодняк')),
                ('id_purpose_of_forests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.purposeofforests', verbose_name='Целевое назначение лесов')),
                ('id_type_forest_growing_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoForest.typeforestgrowingconditions', verbose_name='Тип лесорастительных условий')),
            ],
        ),
    ]
