# Generated by Django 4.1.3 on 2024-06-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0036_alter_fieldcard_end_at_alter_fieldcard_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionregion',
            name='id_method_of_reforestation',
        ),
        migrations.AlterField(
            model_name='fieldcard',
            name='id_point7table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.point7table'),
        ),
    ]
