# Generated by Django 4.1.3 on 2024-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0037_remove_descriptionregion_id_method_of_reforestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcard',
            name='details_regulations',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='реквизиты лесохозяйственного регламента'),
        ),
    ]
