# Generated by Django 4.1 on 2024-05-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0037_remove_descriptionregion_id_method_of_reforestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcard',
            name='end_at',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='заканчивая до'),
        ),
        migrations.AlterField(
            model_name='fieldcard',
            name='start_at',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='начиная с'),
        ),
    ]
