# Generated by Django 4.1 on 2024-05-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0038_alter_fieldcard_end_at_alter_fieldcard_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcard',
            name='id_point7table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.point7table'),
        ),
    ]
