# Generated by Django 4.1 on 2024-07-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0039_alter_fieldcard_id_point7table'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcard',
            name='details_regulations',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='реквизиты лесохозяйственного регламента'),
        ),
    ]
