# Generated by Django 4.1 on 2024-09-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0040_fieldcard_details_regulations'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionregion',
            name='desc_forest_area',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Информация о лесном районе'),
        ),
    ]
