# Generated by Django 4.1.3 on 2023-05-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0041_alter_descriptionregion_year_assignment_land_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point7table2sapling',
            name='breed',
        ),
        migrations.AddField(
            model_name='point7table2sapling',
            name='id_breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.breed', verbose_name='Порода'),
        ),
    ]
