# Generated by Django 4.1 on 2025-03-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0034_alter_sample_sample_area'),
        ('djangoForest', '0041_descriptionregion_desc_forest_area'),
    ]

    operations = [
    ]
