# Generated by Django 4.1.3 on 2023-05-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0042_remove_point7table2sapling_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listregion',
            name='number_region',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
