# Generated by Django 4.1 on 2025-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0043_alter_descriptionregion_year_assignment_land_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OOPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_oopt', models.CharField(max_length=300, verbose_name='ООПТ')),
            ],
        ),
    ]
