# Generated by Django 4.1.3 on 2023-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0044_remove_point7table_breed_point7table_id_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionregion',
            name='breed_composition_sapling_data_surver',
            field=models.CharField(max_length=300, null=True, verbose_name='Породный состав молодняка по данным натурного обследования'),
        ),
        migrations.AddField(
            model_name='descriptionregion',
            name='farm_according_data_survey',
            field=models.CharField(max_length=300, null=True, verbose_name='Хозяйство по данным натурного обследования '),
        ),
    ]
