# Generated by Django 4.1 on 2025-03-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0044_oopt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeForestUsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_using', models.CharField(max_length=300, verbose_name='Виды использования лесов')),
            ],
        ),
    ]
