# Generated by Django 4.1 on 2025-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0045_typeforestusing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseVermin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_phase', models.CharField(max_length=50, verbose_name='Код')),
                ('name_phase', models.CharField(max_length=300, verbose_name='Наименование фаз и стадий развития насекомых и болезней')),
            ],
        ),
    ]
