# Generated by Django 4.1 on 2025-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0046_phasevermin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightUseForestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_right', models.CharField(max_length=150, verbose_name='Название (вид документов на право пользования)')),
            ],
        ),
    ]
