# Generated by Django 4.1.3 on 2023-05-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0046_alter_descriptionregion_year_assignment_land_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point7table',
            name='id_breed',
        ),
        migrations.RemoveField(
            model_name='point7table2sapling',
            name='id_breed',
        ),
        migrations.AddField(
            model_name='point7table',
            name='id_list_region_breed',
            field=models.ForeignKey(default=89, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.list', verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='point7table2sapling',
            name='id_list_region_breed',
            field=models.ForeignKey(default=89, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.list', verbose_name='Порода'),
        ),
    ]
