# Generated by Django 4.1 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0047_rightuseforestarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestDistirct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_district', models.CharField(max_length=500, verbose_name='Наименование лесного района')),
            ],
        ),
    ]
