# Generated by Django 4.1 on 2025-06-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0048_forestdistirct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForestDistirct',
        ),
        migrations.AddField(
            model_name='descriptionregion',
            name='recovery_method',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fieldcard',
            name='id_forest_districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.forestdistricts', verbose_name='Лесные районы РФ'),
        ),
        migrations.AddField(
            model_name='gps',
            name='unique_uid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='list',
            name='unique_uid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='listregion',
            name='unique_uid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='photopoint',
            name='unique_uid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='unique_uid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
