# Generated by Django 4.1.3 on 2023-05-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0048_fieldсard_forest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldсard',
            name='id_point7table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoForest.point7table'),
        ),
        migrations.AddField(
            model_name='point7table',
            name='completeness',
            field=models.CharField(max_length=300, null=True, verbose_name='Полнота'),
        ),
        migrations.AddField(
            model_name='point7table',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='Запас'),
        ),
    ]
