# Generated by Django 4.1.3 on 2023-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0049_fieldсard_id_point7table_point7table_completeness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point7table',
            name='completeness',
        ),
        migrations.RemoveField(
            model_name='point7table',
            name='stock',
        ),
        migrations.AddField(
            model_name='fieldсard',
            name='point7_completeness',
            field=models.CharField(max_length=300, null=True, verbose_name='Полнота'),
        ),
        migrations.AddField(
            model_name='fieldсard',
            name='point7_stock',
            field=models.IntegerField(null=True, verbose_name='Запас'),
        ),
    ]
