# Generated by Django 4.1 on 2025-07-16 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0049_delete_forestdistirct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='unique_uid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='unique_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='listregion',
            name='unique_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='photopoint',
            name='unique_uid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='unique_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
