# Generated by Django 4.1 on 2025-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0050_alter_gps_unique_uid_alter_list_unique_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listregion',
            name='number_region',
            field=models.IntegerField(null=True),
        ),
    ]
