# Generated by Django 4.1.3 on 2023-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoForest', '0050_remove_point7table_completeness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='list',
            name='ratio_composition',
            field=models.IntegerField(null=True, verbose_name='Коэфф. состава'),
        ),
    ]
